# Generated by Django 5.1.3 on 2024-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temporary_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
