# Generated by Django 5.1.3 on 2024-12-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0004_customuser_temporary_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='temporary_field',
        ),
    ]
