# Generated by Django 5.1.3 on 2024-12-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0006_alter_customuser_department_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CHE', 'COMPUTER HARDWARE ENGINEERING'), ('CE', 'CIVIL ENGINEERING'), ('ME', 'MECHANICAL ENGINEERING'), ('IE', 'INSTRUMENTATION ENGINEERING'), ('EE', 'ELECTRONICS ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONICS ENGINEERING'), ('nss', 'NSS'), ('ncc', 'NCC'), ('hostel', 'Hostel'), ('library', 'Library'), ('science lab', 'Science Lab'), ('acedemic sessions', 'Acedemic Sessions')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('hod', 'HOD'), ('tutor', 'Tutor'), ('staff', 'Staff'), ('nss', 'NSS'), ('ncc', 'NCC'), ('hostel', 'Hostel'), ('library', 'Library'), ('science lab', 'Science Lab'), ('acedemic sessions', 'Acedemic Sessions')], default='student', max_length=30),
        ),
    ]
