# Generated by Django 5.1.3 on 2025-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0011_alter_customuser_department_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_approve_status',
            field=models.BooleanField(default=False),
        ),
    ]
