# Generated by Django 5.1.3 on 2025-01-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0012_customuser_auto_approve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auto_approve_status',
        ),
    ]
