# Generated by Django 5.1.3 on 2025-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0013_remove_customuser_auto_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('hod', 'HOD'), ('tutor', 'Tutor'), ('staff', 'Staff'), ('nss', 'NSS'), ('ncc', 'NCC'), ('lab', 'Lab'), ('hostel', 'Hostel'), ('library', 'Library'), ('academics', 'Academics')], default='admin', max_length=10),
        ),
    ]
