# Generated by Django 5.1.3 on 2025-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_approval_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
