# Generated by Django 5.1.3 on 2024-12-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('prn', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('due', 'Due')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
