# Generated by Django 5.1.3 on 2024-12-26 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_tcapplication_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='approvals',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='tcapplication',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_tc_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
