# Generated by Django 5.1.3 on 2024-12-26 11:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_tcapplication_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcapplication',
            name='pending_approval',
            field=models.ManyToManyField(blank=True, related_name='pending_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='due_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='prn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('due', 'Due')], default='pending', max_length=20),
        ),
    ]
