# Generated by Django 5.1.3 on 2024-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_tcapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcapplication',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Transfer Certificate Application', 'verbose_name_plural': 'Transfer Certificate Applications'},
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='prn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
