# Generated by Django 5.1.3 on 2024-12-27 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_tcapplication_created_at_tcapplication_marked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='pending_approval',
        ),
        migrations.AddField(
            model_name='tcapplication',
            name='pending_approval',
            field=models.ManyToManyField(blank=True, help_text='Users required to approve the application.', related_name='tc_pending_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
