# Generated by Django 5.1.3 on 2024-12-27 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_tcapplication_pending_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='rejected_by',
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='tc_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='due_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='pending_approval',
            field=models.ManyToManyField(blank=True, related_name='tc_pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
    ]
