# Generated by Django 5.1.3 on 2024-12-27 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_tcapplication_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='due_list',
            field=models.ManyToManyField(blank=True, help_text='Users who have flagged this application as due.', related_name='tc_due_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
