# Generated by Django 5.1.3 on 2024-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_tcapplication_due_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcapplication',
            name='department',
            field=models.CharField(choices=[('CHE', 'COMPUTER HARDWARE ENGINEERING'), ('CE', 'CIVIL ENGINEERING'), ('ME', 'MECHANICAL ENGINEERING'), ('IE', 'INSTRUMENTATION ENGINEERING'), ('EE', 'ELECTRONICS ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONICS ENGINEERING')], max_length=50),
        ),
    ]
