# Generated by Django 5.1.3 on 2024-12-31 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_tcapplication_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='tc_rejections', to=settings.AUTH_USER_MODEL),
        ),
    ]
