# Generated by Django 5.1.3 on 2024-12-31 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_tcapplication_handled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='processed_by_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles that have already processed this application.', related_name='processed_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
