# Generated by Django 5.1.3 on 2024-12-31 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_tcapplication_processed_by_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tcapplication',
            name='current_processing_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
