# Generated by Django 5.1.3 on 2024-12-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_tcapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='current_processing_role',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='processed_by_roles',
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
