# Generated by Django 5.1.3 on 2025-01-01 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_tcapplication_current_processing_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcapplication',
            name='approved_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have approved this application.', related_name='tc_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='pending_approval',
            field=models.ManyToManyField(blank=True, help_text='Users who are required to approve this application.', related_name='tc_pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tcapplication',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have rejected this application.', related_name='tc_rejections', to=settings.AUTH_USER_MODEL),
        ),
    ]
