# Generated by Django 5.1.3 on 2025-01-01 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_tcapplication_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='due_users',
            field=models.ManyToManyField(blank=True, related_name='due_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
