# Generated by Django 5.1.3 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_tcapplication_due_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='is_uploaded_due',
            field=models.BooleanField(default=False),
        ),
    ]
