# Generated by Django 5.1.3 on 2025-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_tcapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='tcapplication',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
