# Generated by Django 5.1.3 on 2025-01-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_tcapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
