# Generated by Django 5.1.3 on 2025-01-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_uploadedduelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='auto_approval_deadline',
        ),
        migrations.RemoveField(
            model_name='tcapplication',
            name='auto_approved',
        ),
    ]
