# Generated by Django 5.1.3 on 2025-01-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_alter_uploadedduelist_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedduelist',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedduelist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
