# Generated by Django 5.1.3 on 2025-01-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_alter_uploadedduelist_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcapplication',
            name='department',
            field=models.CharField(blank=True, choices=[('CHE', 'COMPUTER HARDWARE ENGINEERING'), ('CE', 'CIVIL ENGINEERING'), ('ME', 'MECHANICAL ENGINEERING'), ('IE', 'INSTRUMENTATION ENGINEERING'), ('EE', 'ELECTRONICS ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONICS ENGINEERING')], max_length=50, null=True),
        ),
    ]
