# Generated by Django 5.1.3 on 2025-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_tcapplication_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcapplication',
            name='forwarded_to_clerk',
            field=models.BooleanField(default=False),
        ),
    ]
