# Generated by Django 5.1.3 on 2025-01-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_tcapplication_forwarded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcapplication',
            name='forwarded_by',
        ),
    ]
