# Generated by Django 5.1.3 on 2025-01-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoApproveSetting',
        ),
    ]
