# Generated by Django 5.1.3 on 2025-01-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeusers', '0002_delete_autoapprovesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApproveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
