# Generated by Django 5.1.3 on 2025-01-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeusers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoApproveSetting',
        ),
    ]
